---

# ----------------------------------------------
# Configura el bluetooth nativo de la cubietruck
# ----------------------------------------------

- name: Copiar fichero brcm_patchram_plus
  copy:
    src:  files/brcm_patchram_plus
    dest: /usr/local/bin/brcm_patchram_plus
    owner: root
    group: root
    mode: 0755

- name: Insertar modulos al arranque
  lineinfile:
    dest: "/etc/modules"
    regexp: "^{{ item }}"
    line: "{{ item }}"
  with_items:
    - "rfcomm"
    - "hci_uart"
    - "bluetooth"
    - "hidp"
#      BNEP me da errores en dmesg, y no lo necesito, asi que fuera
#   - "bnep"

- name: Configurar el audio bluetooth
  lineinfile:
    state: present
    dest: /etc/bluetooth/audio.conf
    insertafter: "^.General"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - line: "Master=true"
      regexp: "^Master"
    - line: "Enable=Control,Source,Socket"
      regexp: "^Enable"
    - line: "AutoConnect=true"
      regexp: "^AutoConnect"

- name: Tarea de runit para arrancar bluetooth
  copy:
    src: files/runit/bluetooth
    dest: /etc/service
    mode: "0755"
    directory_mode: "0755"
