---

# ------------------------------------------------------
# Configura Don Dominio
# ------------------------------------------------------

- name: Variables de entorno
  set_fact:
    dd_domain:     "{{ lookup('env', 'DD_DOMAIN')   }}"
    dd_username:   "{{ lookup('env', 'DD_USERNAME') }}"
    dd_apikey:     "{{ lookup('env', 'DD_APIKEY') }}"

- name: Crear carpeta dondominio
  become: yes
  file:
    dest: /tank/dondominio
    owner: cubie
    group: cubie
    state: directory

- name: Descargar script de renovacion DNS de Don Dominio
  when: dd_domain and dd_username and dd_apikey
  git:
    repo: "https://github.com/dondominio/dondns-bash.git"
    clone: yes
    dest: /tank/dondominio

- name: Cambiar permisos de ejecucion para el script de dondominio
  when: dd_domain and dd_username and dd_apikey
  file:
    path: /tank/dondominio/dondominio/dondomcli.sh
    state: file
    owner: cubie
    group: cubie
    mode: 0750
    
- name: Configuracion de Don Dominio
  when: dd_domain and dd_username and dd_apikey
  template:
    src: templates/dondomcli.conf
    dest: /tank/dondominio/dondominio/dondomcli.conf
    owner: cubie
    group: cubie
    mode: "0640"

- name: Actualizar el dominio cada hora
  when: dd_domain and dd_username and dd_apikey
  cron:
    name: Refrescar el nombre de dominio
    user: cubie
    job: cd /tank/dondominio/dondominio && ./dondomcli.sh -c dondomcli.conf
    minute: 51
    state: present
