---

# ------------------------------------------------------
# Configura Don Dominio
# ------------------------------------------------------

- name: Variables de entorno
  set_fact:
    dd_domain:     "{{ lookup('env', 'DD_DOMAIN')   }}"
    dd_username:   "{{ lookup('env', 'DD_USERNAME') }}"
    dd_apikey:     "{{ lookup('env', 'DD_APIKEY') }}"

- name: Descargar script de renovacion DNS de Don Dominio
  when: dd_domain and dd_username and dd_apikey
  unarchive:
    creates: /home/cubie/dondominio
    copy: no
    src: http://labs.dondominio.com/archives/dondominio-dynamic-ip-0.9.1.tar.gz
    dest: /home/cubie
    owner: cubie
    group: cubie

- name: Cambiar permisos de ejecucion para el script de dondominio
  when: dd_domain and dd_username and dd_apikey
  file:
    path: /home/cubie/dondominio/dondomcli.sh
    state: file
    owner: cubie
    group: cubie
    mode: 0750
    
- name: Configuracion de Don Dominio
  when: dd_domain and dd_username and dd_apikey
  template:
    src: templates/dondomcli.conf
    dest: /home/cubie/dondominio/dondomcli.conf
    owner: cubie
    group: cubie
    mode: "0640"

- name: Actualizar el dominio cada hora
  when: dd_domain and dd_username and dd_apikey
  cron:
    name: Refrescar el nombre de dominio
    user: cubie
    job: cd /home/cubie/dondominio && ./dondomcli.sh -c dondomcli.conf
    minute: 51
    state: present
