---

# ------------------------------------------------------
# Configura minidlna
# ------------------------------------------------------

- name: Configuracion de minidlna
  copy:
    src: files/minidlna.conf
    dest: /etc/minidlna.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reiniciar minidlna

- name: Aumento del numero de handlers de inotify
  copy:
    src: files/10-inotify.conf
    dest: /etc/sysctl.d/10-inotify.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reiniciar sysctl
