---

# Repositorio gstreamer0.10-ffmpeg para ubuntu
# https://launchpad.net/~mc3man/+archive/ubuntu/gstffmpeg-keep
- name: Agregar repositorio de gstreamer0.10-ffmpeg
  apt_repository:
    repo: ppa:mc3man/gstffmpeg-keep
    state: present
    update_cache: yes

- name: Instalacion de paquetes requeridos
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - gstreamer-tools
    - build-essential
    - python-dev
    - python-pip
    - python-gst0.10
    - alsaplayer
    - alsaplayer-text
    - mp3gain
    - gstreamer0.10-plugins-ugly
    - gstreamer0.10-plugins-bad
    - gstreamer0.10-ffmpeg
    - gstreamer0.10-alsa

- name: Copiar mp3gain compilado para armhf
  copy:
    src: bin/mp3gain
    dest: /usr/bin/mp3gain
    owner: root
    group: root
    mode: "0755"

- name: Comprobar que existe el volumen de musica
  lvol:
    vg: tank
    lv: musica
    state: present

- name: Montar el volumen de musica
  mount:
    fstype: ext4
    name: /tank/musica
    src: /dev/mapper/tank-musica
    opts: noatime,nodiratime
    state: mounted
