---

# ----------------------------------------
# Proxy inverso basado en nginx
# ----------------------------------------

- name: Variables de entorno
  set_fact:
    noip_domain: "{{ lookup('env', 'NOIP_DOMAIN') }}"

- name: Crear certificado SSL
  command: openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -subj "/C=ES/ST=Madrid/L=Madrid/O=IT/CN={{ noip_domain }}" -keyout cert.key -out cert.crt
  args:
    chdir: /etc/nginx 
    creates: cert.key

- name: Cargar fichero de configuracion de nginx
  template:
    src: templates/nginx.conf
    dest: /etc/nginx/sites-available/default
  notify: Reiniciar nginx
