---

# -----------------------------------------------
# Playbook que configura y lanza seafile.
#
# Este playbook es solo para cuando seafile ya ha estado instalado
# y configurado en el disco duro.
# Para configrarlo desde cero, seguir la guia de instalacion en
# http://manual.seafile.com/deploy/using_mysql.html
# -----------------------------------------------

- name: Comprobar que el volumen de seafile esta creado
  lvol:
    vg: tank
    lv: seafile
    state: present
  notify: Reiniciar seafile

- name: Montar /tank/seafile
  mount:
    fstype: ext4
    name: /tank/seafile
    src: /dev/mapper/tank-seafile
    opts: noatime,nodiratime
    state: mounted
  notify: Reiniciar seafile

- name: Copiar los scripts de supervisor
  copy:
    src: files/start-seafile.conf
    dest: /etc/supervisor/conf.d/start-seafile.conf
  notify: Reiniciar supervisor

- name: Dar al datastore los permisos correctos
  file:
    dest: /tank/seafile
    owner: www-data
    group: www-data
    recurse: yes
  notify: Reiniciar seafile

