---

# -----------------------------------------------
# Playbook que configura y lanza seafile.
#
# Este playbook es solo para cuando seafile ya ha estado instalado
# y configurado en el disco duro.
# Para configrarlo desde cero, seguir la guia de instalacion en
# http://manual.seafile.com/deploy/using_mysql.html
# -----------------------------------------------

- name: Variables de entorno
  set_fact:
    dd_domain: "{{ lookup('env', 'DD_DOMAIN') }}"

# Requerido para soportar seafile con nginx (ver
# http://manual.seafile.com/deploy/deploy_with_nginx.html
- name: Instalar python-flup
  apt:
    name: python-flup
    state: installed

- name: Configurar logrotate para los logs de Seafile
  copy:
    src: files/seafile.logrotate
    dest: /etc/logrotate.d/seafile
    mode: 0644

- name: Comprobar que el volumen de seafile esta creado
  lvol:
    vg: tank
    lv: seafile
    state: present
  notify: Reiniciar seafile

- name: Montar /tank/seafile
  mount:
    fstype: ext4
    name: /tank/seafile
    src: /dev/mapper/tank-seafile
    opts: noatime,nodiratime
    state: mounted
  notify: Reiniciar seafile

- name: Dar al datastore los permisos correctos
  file:
    dest: /tank/seafile
    owner: www-data
    group: www-data
    recurse: yes

- name: Fijar el nombre de servidor
  lineinfile:
    dest: /tank/seafile/ccnet/ccnet.conf
    regexp: ^SERVICE_URL
    line: SERVICE_URL = https://{{ dd_domain }}:8443
  notify: Reiniciar seafile

- name: Copiar los scripts de runit
  copy:
    src: files/runit/seafile
    dest: /etc/service
    mode: "0755"
    directory_mode: "0755"

