---

# ------------------------------------------------------
# Prepara los volumenes logicos basicos
# ------------------------------------------------------

- name: Asegurarse de que el VG tank existe
  lvg:
    vg: tank
    state: present
    pvs: /dev/sda

- name: Asegurarse de que existen los volumenes basicos
  lvol:
    vg: tank
    lv: "{{ item }}"
    state: present
  with_items:
    - top
    - log
    - home

- name: Montar /tank, /log y /home
  mount:
    fstype: ext4
    name: "{{ item.path }}"
    src: /dev/mapper/tank-{{ item.volume }}
    opts: noatime,nodiratime
    state: mounted
  with_items:
    - path: /tank
      volume: top
    - path: /var/log
      volume: log
    - path: /home
      volume: home

- name: Dar los permisos correctos a /tank
  file:
    dest: /tank
    owner: cubie
    group: services
    mode: "0755"
    state: directory

