---

# ----------------------------------------------
# Configura VNC sobre LXDE y un servidor framebuffer
# ----------------------------------------------

- name: Variables de entorno
  set_fact:
    vnc_password: "{{ lookup('env', 'VNC_PASSWORD') }}"

- name: Cambia el servidor X por defecto por Xvfb
  lineinfile:
    dest: /etc/lightdm/lightdm.conf
    state: present
    regexp: "^xserver-command"
    line: "xserver-command=/etc/X11/xinit/xserverrc"
    insertafter: "^.SeatDefaults"

- name: Se asegura de que la ruta a xserverrc existe
  file:
    dest: "/etc/X11/xinit"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copia el fichero xserverrc
  template:
    src: templates/xserverrc
    dest: /etc/X11/xinit/xserverrc
    owner: root
    group: root
    mode: 0755
