---

- name: Reiniciar sysctl
  command: sysctl --system
  
- name: Reiniciar iptables
  service:
    name: netfilter-persistent
    state: restarted

- name: Reiniciar resolvconf
  service:
    name: resolvconf
    state: restarted

- name: Reiniciar dnsmasq
  service:
    name: dnsmasq
    state: restarted

- name: Reiniciar ddclient
  service:
    name: ddclient
    state: restarted

- name: Reiniciar supervisor
  service:
    name: supervisor
    state: restarted

- name: Reiniciar minidlna
  service:
    name: minidlna
    state: restarted

- name: Reiniciar mysql
  service:
    name: mysql
    state: restarted

- name: Reiniciar nginx
  service:
    name: nginx
    state: restarted

- name: Reiniciar samba
  service:
    name: samba
    state: restarted

- name: Reiniciar apparmor
  service:
    name: apparmor
    state: restarted

- name: Reiniciar seafile
  command: sv restart seafile

- name: Reiniciar transmission
  service:
    name: transmission
    state: restarted
