---

# -----------------------------------------------------------
# Este script requiere varias variables de entorno:
#
# - WLAN0_ADDRESS: Direccion IP de la interfaz wlan0
# - NOIP_DOMAIN:   Dominio dinamico registrado en noip.org.
# - NOIP_USERNAME: Nombre de usuario de noip.
# - NOIP_PASSWORD: Clave de noip.
# -----------------------------------------------------------

- hosts: microserver

  tasks:

    - include: tasks/packages.yml
      tags:
        - bootstrap
        - packages

    - include: tasks/system.yml
      tags:
        - bootstrap
        - system

    - include: tasks/firewall.yml
      tags:
        - bootstrap
        - firewall

    - include: tasks/dnsmasq.yml
      tags:
        - bootstrap
        - dnsmasq

    - include: tasks/ddclient.yml
      tags:
        - bootstrap
        - ddclient

    - include: tasks/users.yml
      tags:
        - bootstrap
        - users

    - include: tasks/storage.yml
      tags: storage

    - include: tasks/audio.yml
      tags:
        - audio
        - mopidy

      # Para escanear la biblioteca local:
      # supervisorctl restart mopidy_scan
    - include: tasks/mopidy.yml
      tags: mopidy

    - include: tasks/minidlna.yml
      tags: minidlna

    - include: tasks/mysql.yml
      tags:
        - mysql
        - seafile

    - include: tasks/seafile.yml
      tags: seafile

  handlers:

    - include: handlers/main.yml
      tags: always
