---

- hosts: microserver

  tasks:

    - include: tasks/packages.yml
      tags:
        - bootstrap
        - packages

    - include: tasks/system.yml
      tags:
        - bootstrap
        - system

    - include: tasks/firewall.yml
      tags:
        - bootstrap
        - firewall

    - include: tasks/dnsmasq.yml
      tags:
        - bootstrap
        - dnsmasq

#   Ya no usamos ddclient, sino CloudFlare
#    - include: tasks/ddclient.yml
#      tags:
#        - bootstrap
#        - ddclient

#    Ya no usamos Don Dominio, sino CloudFlare
#    - include: tasks/dondominio.yml
#      tags:
#        - bootstrap
#        - dondominio

    - include: tasks/users.yml
      tags:
        - bootstrap
        - users

    - include: tasks/storage.yml
      tags:
        - bootstrap
        - storage

    - include: tasks/audio.yml
      tags:
        - bootstrap
        - audio
        - mopidy

    - include: tasks/cloudflare.yml
      tags:
        - bootstrap
        - cloudflare

    - include: tasks/vnc.yml
      tags:
        - bootstrap
        - vnc

#    - include: tasks/bluetooth.yml
#      tags:
#        - bootstrap
#        - bluetooth

      # Para escanear la biblioteca local:
      # supervisorctl restart mopidy_scan
    - include: tasks/mopidy.yml
      tags:
        - mopidy

    - include: tasks/minidlna.yml
      tags:
        - minidlna

    - include: tasks/mysql.yml
      tags:
        - mysql

    - include: tasks/nginx.yml
      tags:
        - seafile
        - torrent
        - nginx
#        - plex

    - include: tasks/seafile.yml
      tags:
        - seafile

    - include: tasks/torrent.yml
      tags:
        - torrent

    - include: tasks/samba.yml
      tags:
        - samba

    - include: tasks/syncthing.yml
      tags:
        - syncthing

#     Los clientes buenos de plex son de pago, paso
#    - include: tasks/plex.yml
#      tags:
#        - plex

#    - include: tasks/java.yml
#      tags:
#        - java
#        - madsonic

#    - include: tasks/madsonic.yml
#      tags:
#        - madsonic

    - include: tasks/cherrymusic.yml
      tags:
        - cherrymusic

    - include: tasks/tools.yml
      tags:
        - torrent
        - tools

  handlers:

    - include: handlers/main.yml
      tags: always
